#!/usr/bin/env python3
"""
One-time generator: reads tools/taxonomy-sources/math_taxonomy.json
(the merged K-8 + HS Common Core taxonomy) and emits
supabase-teacherportal-math-taxonomy-seed.sql — a PL/pgSQL seed
script for the grades_courses / domains / math_topics / taxonomy
tables created by supabase-teacherportal-math-taxonomy-v2-upgrade.sql.

A PL/pgSQL DO block (rather than plain INSERT statements with
name-based lookups) is used because a couple of math_topics names
("Volume", "Equivalent Expressions") legitimately recur under two
different domains — RETURNING ... INTO a local variable at insert
time avoids any ambiguity about which math_topics row a given
taxonomy row should reference.

Re-run this script whenever math_taxonomy.json changes, then re-run
the generated SQL file in the Supabase SQL editor. The generated
seed is guarded to no-op if the taxonomy table already has rows, so
it's safe to run more than once against the same database.

Usage: python3 tools/generate-math-taxonomy-seed.py
"""
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TAXONOMY_JSON = os.path.join(REPO_ROOT, "tools", "taxonomy-sources", "math_taxonomy.json")
OUTPUT_SQL = os.path.join(REPO_ROOT, "supabase-teacherportal-math-taxonomy-seed.sql")

# Domain display order: roughly the K-8 grade-band progression, then
# the HS conceptual categories (Geometry & Statistics & Probability
# already appear earlier from K-8) in their official CCSS order.
DOMAIN_SORT_ORDER = [
    "Counting & Cardinality",
    "Operations & Algebraic Thinking",
    "Number & Operations in Base Ten",
    "Number & Operations—Fractions",
    "Measurement & Data",
    "Geometry",
    "Ratios & Proportional Relationships",
    "The Number System",
    "Expressions & Equations",
    "Statistics & Probability",
    "Number & Quantity",
    "Algebra",
    "Functions",
]


def sql_str(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def main():
    with open(TAXONOMY_JSON) as f:
        data = json.load(f)

    grade_courses = data["gradeCourses"]
    domains = data["domains"]
    topics = data["topics"]

    missing = [d for d in domains if d not in DOMAIN_SORT_ORDER]
    if missing:
        raise SystemExit(f"DOMAIN_SORT_ORDER is missing domain(s): {missing}")

    lines = []
    lines.append("-- =============================================================")
    lines.append("-- Teacher Portal: Math Taxonomy Seed Data")
    lines.append("-- Run this in the Supabase SQL Editor AFTER")
    lines.append("-- supabase-teacherportal-math-taxonomy-v2-upgrade.sql")
    lines.append("--")
    lines.append(f"-- Auto-generated by tools/generate-math-taxonomy-seed.py from")
    lines.append("-- tools/taxonomy-sources/math_taxonomy.json. Do not hand-edit —")
    lines.append("-- edit the source JSON (or the source spreadsheets) and")
    lines.append("-- regenerate instead.")
    lines.append("--")
    lines.append(f"-- Seeds {len(grade_courses)} grades/courses, {len(domains)} domains,")
    lines.append(f"-- {len(topics)} math topics, and "
                  f"{sum(len(t['courses']) for t in topics)} taxonomy combinations.")
    lines.append("-- =============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")

    gc_var = {}
    for i, gc in enumerate(grade_courses):
        gc_var[gc] = f"gc_{i}"
        lines.append(f"  {gc_var[gc]} int;")

    d_var = {}
    for i, d in enumerate(domains):
        d_var[d] = f"d_{i}"
        lines.append(f"  {d_var[d]} int;")

    t_var = {}
    for i in range(len(topics)):
        t_var[i] = f"t_{i}"
        lines.append(f"  {t_var[i]} int;")

    lines.append("BEGIN")
    lines.append("  -- No-op if this has already been seeded.")
    lines.append("  IF EXISTS (SELECT 1 FROM taxonomy LIMIT 1) THEN")
    lines.append("    RAISE NOTICE 'taxonomy already seeded, skipping.';")
    lines.append("    RETURN;")
    lines.append("  END IF;")
    lines.append("")

    lines.append("  -- Grades/Courses")
    for i, gc in enumerate(grade_courses):
        lines.append(
            f"  INSERT INTO grades_courses (name, sort_order) VALUES "
            f"({sql_str(gc)}, {i}) RETURNING id INTO {gc_var[gc]};"
        )
    lines.append("")

    lines.append("  -- Domains")
    for d in domains:
        order = DOMAIN_SORT_ORDER.index(d)
        lines.append(
            f"  INSERT INTO domains (name, sort_order) VALUES "
            f"({sql_str(d)}, {order}) RETURNING id INTO {d_var[d]};"
        )
    lines.append("")

    lines.append("  -- Math Topics")
    for i, t in enumerate(topics):
        lines.append(
            f"  INSERT INTO math_topics (name) VALUES "
            f"({sql_str(t['topic'])}) RETURNING id INTO {t_var[i]};"
        )
    lines.append("")

    lines.append("  -- Taxonomy (valid Grade/Course + Domain + Math Topic combinations)")
    sort_order = 0
    for i, t in enumerate(topics):
        for course in t["courses"]:
            sort_order += 1
            lines.append(
                f"  INSERT INTO taxonomy (grade_course_id, domain_id, math_topic_id, "
                f"ccss_reference, sort_order) VALUES "
                f"({gc_var[course['gradeCourse']]}, {d_var[t['domain']]}, {t_var[i]}, "
                f"{sql_str(course.get('standards'))}, {sort_order});"
            )

    lines.append("END $$;")
    lines.append("")

    with open(OUTPUT_SQL, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUTPUT_SQL}")
    print(f"  {len(grade_courses)} grades/courses, {len(domains)} domains, "
          f"{len(topics)} math topics, "
          f"{sum(len(t['courses']) for t in topics)} taxonomy rows")


if __name__ == "__main__":
    main()
